- name: Create configuration files
  template: src={{ item }}.j2 dest=/etc/{{ item }} owner=root group=root mode=0644
  with_items:
    - php.ini
    - php-fpm.conf
    - php-fpm.d/www.conf

- name: reload php-fpm
  service: name=php-fpm state=reloaded enabled=yes
